language: generic

sudo: required

services:
  - docker

before_deploy:
  - mkdir -p before-deploy # zip에 포함시킬 파일들을 담을 디렉토리 생성
  - cp Dockerfile before-deploy/     # Dockerfile 복사하기 
  - cp appspec.yml before-deploy/    # CodeDeploy 에게 필요한 appspec.yml 파일
  - cd before-deploy && zip -r before-deploy * # before-deploy로 이동후 전체 압축
  - cd ../ && mkdir -p deploy # 상위 디렉토리로 이동후 deploy 디렉토리 생성
  - mv before-deploy/before-deploy.zip deploy/bolier-CD.zip # deploy로 zip파일 이동

script:
  - docker run -e CI=true dudckd/bolier npm run test

deploy:
  provider: codedeploy
  region: "ap-northeast-2"
  application: "test"
  deployment_group: "test_test"
  key: bolier-CD.zip
  bucket: wooyc
  bundle_type: zip
  on:
    branch: main
  
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY