version: "3.3"
services: 
  nest:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: nest
    ports: 
      - "5000:5000"
    volumes:
      - /app/node_modules
      - .:/app

  mysql:
    build: ./mysql
    restart: always
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: asdfzxcv
      MYSQL_DATABASE: bolier